
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  build:
    name:     "main"
    arch:     "amd64"
    system:   "linux,darwin"
    mod:      "none"
    packSrc:  "resource,manifest"
#    version:  "auth.0.0"
    output:   "./bin"
    extra:    ""
  docker:
    build: "-a amd64 -s linux -p temp -ew"
  gen:
    dao:
      - link:   "mysql:unibee:changeme@tcp(127.0.0.1:3307)/unibee?loc=Local&parseTime=true"
        group: "default"
        daoPath:  "dao/default"
        doPath:  "model/do/default"
        entityPath:  "model/entity/default"
        noModelComment: false
        descriptionTag: true
#        tables: "user_admin_note"
env: local

server:
  address:     ":8088"
  domainPath: "http://127.0.0.1:8088"
  tokenKey: "3^&secret-key-for-UniBee*1!8*"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

auth:
  login:
    expire: 3600

logger:
  level : "all"
  stdout: true

database:
  default:
    link:    "mysql:unibee:changeme@tcp(127.0.0.1:3306)/unib"
    debug:   false
    type:    mysql
    charset:  "utf8mb4"

# Redis Stage
redis:
  default:
    address: 127.0.0.1:6379
    pass: changeme
    maxIdle: 500
    minIdle: 10
    idleTimeout: 1d
